config/routes.rb
Temp::Application.routes.draw do
    root :to => 'home#public'

    match '/home' => 'home#index', :as => :home
    match '/home/about' => 'home#about', :as => :about

    match '/auth/:provider/callback'  => 'sessions#create'
    match '/auth/failure'             => 'sessions#failure'
    match '/signout'                  => 'sessions#destroy',  :as => :signout
    match '/signin'                   => 'sessions#new',      :as => :signin

    get   '/home/event/web_crawler'  => 'event#web_crawler',   :as => :web_crawler_event

    get   '/home/event/new'         => 'event#new',     :as => :new_event
    post  '/home/event/create'      => 'event#create',  :as => :create_event
    get   '/home/event/:id'         => 'event#show',    :as => :show_event
    get   '/home/event/delete/:id'  => 'event#delete',  :as => :delete_event
    get   '/home/event/:id/update_name' => 'event#update_name', :as => :update_name_event
    post  '/home/event/:id/update_name_save' => 'event#update_name_save', :as => :update_name_save_event
    get   '/home/event/:id/update_type' => 'event#update_type', :as => :update_type_event
    post  '/home/event/:id/update_type_save' => 'event#update_type_save', :as => :update_type_save_event
    get   '/home/event/:id/update_start_time' => 'event#update_start_time', :as => :update_start_time_event
    post  '/home/event/:id/update_start_time_save' => 'event#update_start_time_save', :as => :update_start_time_save_event
    get   '/home/event/:id/update_end_time' => 'event#update_end_time', :as => :update_end_time_event
    post  '/home/event/:id/update_end_time_save' => 'event#update_end_time_save', :as => :update_end_time_save_event
    get   '/home/event/:id/update_cost' => 'event#update_cost', :as => :update_cost_event
    post  '/home/event/:id/update_cost_save' => 'event#update_cost_save', :as => :update_cost_save_event
    get   '/home/event/:id/update_location' => 'event#update_location', :as => :update_location_event
    post  '/home/event/:id/update_location_save' => 'event#update_location_save', :as => :update_location_save_event
    get   '/home/event/:id/update_description' => 'event#update_description', :as => :update_description_event
    post  '/home/event/:id/update_description_save' => 'event#update_description_save', :as => :update_description_save_event
    get   '/home/event/:id/update_registration_deadline' => 'event#update_registration_deadline', :as => :update_registration_deadline_event
    post  '/home/event/:id/update_registration_deadline_save' => 'event#update_registration_deadline_save', :as => :update_registration_deadline_save_event
    get   '/home/event/:id/update_food' => 'event#update_food', :as => :update_food_event
    post  '/home/event/:id/update_food_save' => 'event#update_food_save', :as => :update_food_save_event

    get   '/home/myevent/show'  => 'myevent#show',   :as => :show_myevent
    get  '/home/myevent/add/:id' => 'myevent#add',   :as => :add_myevent
    get   '/home/myevent/remove/:id' =>  'myevent#remove', :as => :remove_myevent 

    get  '/home/my_recommendation'  => 'home#my_recommendation', :as => :my_recommendation_home
    get   '/home/search' => 'home#search', :as => :search_home
    post  '/home/search_results' => 'home#search_results', :as => :search_results_home

    get   '/home/event/:id/host/new'  => 'host#new',  :as => :new_host
    post  '/home/event/:id/host/create' => 'host#create', :as => :create_host
    get   '/home/event/:id/host/delete/' =>'host#delete', :as => :delete_host

    get   '/home/event/:id/sponsor/new'  => 'sponsor#new',  :as => :new_sponsor
    post  '/home/event/:id/sponsor/create' => 'sponsor#create', :as => :create_sponsor
    get   '/home/event/:id/sponsor/delete/' =>'sponsor#delete', :as => :delete_sponsor

    get   '/home/event/:id/speaker/new'  => 'speaker#new',  :as => :new_speaker
    post  '/home/event/:id/speaker/create' => 'speaker#create', :as => :create_speaker
    get   '/home/event/:id/speaker/delete/' =>'speaker#delete', :as => :delete_speaker

    get   '/home/event/:id/artist/new'  => 'artist#new',  :as => :new_artist
    post  '/home/event/:id/artist/create' => 'artist#create', :as => :create_artist
    get   '/home/event/:id/artist/delete/' =>'artist#delete', :as => :delete_artist

    get  '/home/person/new'    => 'person#new',    :as => :new_person
    post '/home/person/create' => 'person#create', :as => :create_person
    get  '/home/person/delete/:id'  => 'person#delete',  :as => :delete_person 
    get  '/home/person/:id'   =>  'person#show',  :as =>  :show_person
    get   '/home/person/:id/update_name' => 'person#update_name', :as => :update_name_person
    post  '/home/person/:id/update_name_save' => 'person#update_name_save', :as => :update_name_save_person
    get   '/home/person/:id/update_address' => 'person#update_address', :as => :update_address_person
    post  '/home/person/:id/update_address_save' => 'person#update_address_save', :as => :update_address_save_person
    get   '/home/person/:id/update_email' => 'person#update_email', :as => :update_email_person
    post  '/home/person/:id/update_email_save' => 'person#update_email_save', :as => :update_email_save_person
    get   '/home/person/:id/update_phone' => 'person#update_phone', :as => :update_phone_person
    post  '/home/person/:id/update_phone_save' => 'person#update_phone_save', :as => :update_phone_save_person

end

app/models/person.rb
class Person < ActiveRecord::Base
	validates_presence_of :name
	validates_uniqueness_of :name
	
	has_many :hosts
	has_many :speakers
	has_many :artists
	has_many :sponsors

end

app/controllers/person_controller.rb
class PersonController < ApplicationController

	def show
		@id = params[:id]
		@person = Person.find_by_id(@id)
		if !@person
			flash[:warning] = "Invalid Person"
			redirect_to home_path and return
		end
	end

	def new
		@person = Person.new
	end

	def create
		@id = params[:id]
		@form = params[:person]
		@person = Person.new
		@person.name = @form[:name]
		@person.email = @form[:email]
		@person.phone = @form[:phone]
		@person.address = @form[:address]
		if @person.save
			flash[:notice] = "Person has been created"
			redirect_to home_path and return #maybe change this
		else
			flash[:warning] = "Invalid Person"
			redirect_to new_person_path and return
		end
	end

	def update_name
		@person = Person.new
	end

	def update_name_save
		@id = params[:id]
		@form = params[:person]
		@person = Person.find_by_id(@id)
		if !@person
			flash[:warning] = "Person does not exist"
		else
			@person.name = @form[:name]
			if@person.save
				flash[:notice] = "Person name updated"
				redirect_to show_person_path and return
			else
				flash[:warning] = "Invalid Name"
				redirect_to update_name_person_path and return
			end
		end
	end

	def update_address
		@person = Person.new
	end

	def update_address_save
		@id = params[:id]
		@form = params[:person]
		@person = Person.find_by_id(@id)
		if !@person
			flash[:warning] = "Person does not exist"
		else
			@person.address = @form[:address]
			if@person.save
				flash[:notice] = "Person address updated"
				redirect_to show_person_path and return
			else
				flash[:warning] = "Invalid address"
				redirect_to update_address_person_path and return
			end
		end
	end
	
	def update_email
		@person = Person.new
	end

	def update_email_save
		@id = params[:id]
		@form = params[:person]
		@person = Person.find_by_id(@id)
		if !@person
			flash[:warning] = "Person does not exist"
		else
			@person.email = @form[:email]
			if@person.save
				flash[:notice] = "Person email updated"
				redirect_to show_person_path and return
			else
				flash[:warning] = "Invalid email"
				redirect_to update_email_person_path and return
			end
		end
	end
	
	def update_phone
		@person = Person.new
	end

	def update_phone_save
		@id = params[:id]
		@form = params[:person]
		@person = Person.find_by_id(@id)
		if !@person
			flash[:warning] = "Person does not exist"
		else
			@person.phone = @form[:phone]
			if@person.save
				flash[:notice] = "Person phone updated"
				redirect_to show_person_path and return
			else
				flash[:warning] = "Invalid Phone"
				redirect_to update_phone_person_path and return
			end
		end
	end
	

	def delete
		@id = params[:id]
		@person = Person.find_by_id(@id)
		if !@person
			flash[:warning] = "Invalid Person"
		else
			@sponsor = Sponsor.find_by_sponsorName(@person.name)
			if @sponsor
				@sponsor.destroy
			end
			@person.destroy
			flash[:notice] = "Person has been deleted"
		end
		redirect_to home_path and return

	end

end

app/views/person/new.html.haml
= form_for @person, :url => { :action => "create"}, :html => {:class => "nifty_form"} do |f|
	= f.label :name
	= f.text_field :name
	= f.label :email
	= f.text_field :email
	= f.label "Phone Number ex: 0123456789"
	= f.text_field :phone
	= f.label :address
	= f.text_field :address
	%br
	%br

	=f.submit "Create", :class => "btn btn-success"

	%br
	%br
	%br
	=link_to "Back", home_path, :class => "btn btn-primary"

app/views/person/show.html.haml
Name:
%br
=@person.name

=link_to "Update Name", update_name_person_path, class: "btn btn-mini"
%br
%br
Email:
%br
=@person.email
=link_to "Update Email", update_email_person_path, class: "btn btn-mini"

%br
%br
Phone Number:
%br
=@person.phone
=link_to "Update Phone Number", update_phone_person_path, class: "btn btn-mini"

%br
%br
Address:
%br
=@person.address
=link_to "Update Address", update_address_person_path, class: "btn btn-mini"


%br
%br

=link_to "Delete", delete_person_path, class: "btn btn-mini"
%br
%br

%br
= link_to "Back", home_path, class: "btn btn-primary"

app/views/person/update_address.html.haml
= form_for @person, :url => { :action => "update_address_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Address"
	= f.text_field :address
	%br
	%br

	=f.submit "Update Address", :class => "btn btn-success"

%br
%br
= link_to "Back", show_person_path, :class => "btn btn-primary"

app/views/person/update_email.html.haml
= form_for @person, :url => { :action => "update_email_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Email"
	= f.text_field :email
	%br
	%br

	=f.submit "Update Email", :class => "btn btn-success"

%br
%br
= link_to "Back", show_person_path, :class => "btn btn-primary"

app/views/person/update_name.html.haml
= form_for @person, :url => { :action => "update_name_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Name"
	= f.text_field :name
	%br
	%br

	=f.submit "Update Name", :class => "btn btn-success"

%br
%br
= link_to "Back", show_person_path, :class => "btn btn-primary"

app/views/person/update_phone.html.haml
= form_for @person, :url => { :action => "update_phone_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Phone Number ex: 0123456789"
	= f.text_field :phone
	%br
	%br

	=f.submit "Update Phone", :class => "btn btn-success"

%br
%br
= link_to "Back", show_person_path, :class => "btn btn-primary"