config/routes.rb
Temp::Application.routes.draw do
    root :to => 'home#public'

    match '/home' => 'home#index', :as => :home
    match '/home/about' => 'home#about', :as => :about

    match '/auth/:provider/callback'  => 'sessions#create'
    match '/auth/failure'             => 'sessions#failure'
    match '/signout'                  => 'sessions#destroy',  :as => :signout
    match '/signin'                   => 'sessions#new',      :as => :signin

    get   '/home/event/web_crawler'  => 'event#web_crawler',   :as => :web_crawler_event

    get   '/home/event/new'         => 'event#new',     :as => :new_event
    post  '/home/event/create'      => 'event#create',  :as => :create_event
    get   '/home/event/:id'         => 'event#show',    :as => :show_event
    get   '/home/event/delete/:id'  => 'event#delete',  :as => :delete_event
    get   '/home/event/:id/update_name' => 'event#update_name', :as => :update_name_event
    post  '/home/event/:id/update_name_save' => 'event#update_name_save', :as => :update_name_save_event
    get   '/home/event/:id/update_type' => 'event#update_type', :as => :update_type_event
    post  '/home/event/:id/update_type_save' => 'event#update_type_save', :as => :update_type_save_event
    get   '/home/event/:id/update_start_time' => 'event#update_start_time', :as => :update_start_time_event
    post  '/home/event/:id/update_start_time_save' => 'event#update_start_time_save', :as => :update_start_time_save_event
    get   '/home/event/:id/update_end_time' => 'event#update_end_time', :as => :update_end_time_event
    post  '/home/event/:id/update_end_time_save' => 'event#update_end_time_save', :as => :update_end_time_save_event
    get   '/home/event/:id/update_cost' => 'event#update_cost', :as => :update_cost_event
    post  '/home/event/:id/update_cost_save' => 'event#update_cost_save', :as => :update_cost_save_event
    get   '/home/event/:id/update_location' => 'event#update_location', :as => :update_location_event
    post  '/home/event/:id/update_location_save' => 'event#update_location_save', :as => :update_location_save_event
    get   '/home/event/:id/update_description' => 'event#update_description', :as => :update_description_event
    post  '/home/event/:id/update_description_save' => 'event#update_description_save', :as => :update_description_save_event
    get   '/home/event/:id/update_registration_deadline' => 'event#update_registration_deadline', :as => :update_registration_deadline_event
    post  '/home/event/:id/update_registration_deadline_save' => 'event#update_registration_deadline_save', :as => :update_registration_deadline_save_event
    get   '/home/event/:id/update_food' => 'event#update_food', :as => :update_food_event
    post  '/home/event/:id/update_food_save' => 'event#update_food_save', :as => :update_food_save_event

    get   '/home/myevent/show'  => 'myevent#show',   :as => :show_myevent
    get  '/home/myevent/add/:id' => 'myevent#add',   :as => :add_myevent
    get   '/home/myevent/remove/:id' =>  'myevent#remove', :as => :remove_myevent 

    get  '/home/my_recommendation'  => 'home#my_recommendation', :as => :my_recommendation_home
    get   '/home/search' => 'home#search', :as => :search_home
    post  '/home/search_results' => 'home#search_results', :as => :search_results_home

    get   '/home/event/:id/host/new'  => 'host#new',  :as => :new_host
    post  '/home/event/:id/host/create' => 'host#create', :as => :create_host
    get   '/home/event/:id/host/delete/' =>'host#delete', :as => :delete_host

    get   '/home/event/:id/sponsor/new'  => 'sponsor#new',  :as => :new_sponsor
    post  '/home/event/:id/sponsor/create' => 'sponsor#create', :as => :create_sponsor
    get   '/home/event/:id/sponsor/delete/' =>'sponsor#delete', :as => :delete_sponsor

    get   '/home/event/:id/speaker/new'  => 'speaker#new',  :as => :new_speaker
    post  '/home/event/:id/speaker/create' => 'speaker#create', :as => :create_speaker
    get   '/home/event/:id/speaker/delete/' =>'speaker#delete', :as => :delete_speaker

    get   '/home/event/:id/artist/new'  => 'artist#new',  :as => :new_artist
    post  '/home/event/:id/artist/create' => 'artist#create', :as => :create_artist
    get   '/home/event/:id/artist/delete/' =>'artist#delete', :as => :delete_artist

    get  '/home/person/new'    => 'person#new',    :as => :new_person
    post '/home/person/create' => 'person#create', :as => :create_person
    get  '/home/person/delete/:id'  => 'person#delete',  :as => :delete_person 
    get  '/home/person/:id'   =>  'person#show',  :as =>  :show_person
    get   '/home/person/:id/update_name' => 'person#update_name', :as => :update_name_person
    post  '/home/person/:id/update_name_save' => 'person#update_name_save', :as => :update_name_save_person
    get   '/home/person/:id/update_address' => 'person#update_address', :as => :update_address_person
    post  '/home/person/:id/update_address_save' => 'person#update_address_save', :as => :update_address_save_person
    get   '/home/person/:id/update_email' => 'person#update_email', :as => :update_email_person
    post  '/home/person/:id/update_email_save' => 'person#update_email_save', :as => :update_email_save_person
    get   '/home/person/:id/update_phone' => 'person#update_phone', :as => :update_phone_person
    post  '/home/person/:id/update_phone_save' => 'person#update_phone_save', :as => :update_phone_save_person

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def public

  end

  def about
  	
  end

  def index
  	@events = Event.all
  	@persons = Person.all
  end

  def search
    @search = Event.all
  end

  def search_results
    @form = params[:search].to_s
    #@search = Event.all(:conditions => ["name like :form|| location like :form || cost like :form || description like :form || food like :form || event_type like :form", {:form => "@form"}])
    @search = Event.find(:all, :conditions => ['name =? OR cost =? OR location =? OR description =? OR food =? OR event_type =?', @form, @form, @form, @form, @form, @form])
    #@search_person = Person.all(:conditions => ["name like @form || email like @form || address like @form"])
    @search_person = Person.find(:all, :conditions => ['name =? OR email =? OR address =?', @form, @form, @form])
    #@search = Event.find(:all, :conditions => ['name LIKE? OR event_start_time LIKE? OR event_end_time LIKE? OR cost LIKE? OR location LIKE? OR description LIKE? OR registration_deadline LIKE? OR food LIKE? OR event_type LIKE?', @form, @form, @form, @form, @form, @form, @form, @form, @form])
    #@search_person = Person.find(:all, :conditions => ['name LIKE? OR email LIKE? OR phone LIKE? OR address LIKE?', @form, @form, @form, @form])
    @join = Person.find(:all, :conditions => ['name =?', @form])
  end

  def my_recommendation
    @myevents = Myevent.find_all_by_user_id(current_user.id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
University of Illinois at Urbana-Champaign
%br
CS 411 Fall 2012
%br
%br
%br
Copyright 
&copy
%br
%br

Harrison Yu
%br
Michal Szymulanski
%br
Erik Chen
%br
Simon Huynh

%br
%br
=link_to "Back to Front Page", root_path, class: "btn btn-primary"
%br
%br
%br
%br
%br

app/views/home/index.html.haml
%br
= link_to "Create a new event", new_event_path, class: "btn btn-success"

-@erik = 'Erik Chen'
-@harrison = 'Harrison Yu'
%br
%br
-if User.find_by_id(current_user.id).name == @erik || User.find_by_id(current_user.id).name == @harrison
  =link_to "Webparser", web_crawler_event_path, class: "btn btn-inverse"

%br
%br

/= link_to "Search", search_home_path, class: "btn btn-inverse"
%br
%br
%br

%table.table.table-bordered
  %thead
    %tr               
      %th Name:
      %th Add to MyEvents
      -if User.find_by_id(current_user.id).name == @erik || User.find_by_id(current_user.id).name == @harrison
        %th Delete

  %tbody
    - @events.each do |e|
      %tr
        %td 
          = link_to e.name, show_event_path(e.id), class: "linkify-td"
        %td
          = link_to "Add to MyEvents", add_myevent_path(e.id), class: "btn"
        -if User.find_by_id(current_user.id).name == @erik || User.find_by_id(current_user.id).name == @harrison
          %td
            = link_to "Delete", delete_event_path(e.id), class: "btn btn-danger"
%br


%br
<font = 5> People: </font>
%br
%br
-@persons.each do |h|
  %tr
    %td
      = link_to h.name, show_person_path(h.id), class: "linkify-td"
%br
%br
%br
= link_to "Create New Person", new_person_path, class: "btn"
%br
%br
%br
=link_to "Back", root_path, class: "btn btn-primary"
%br
%br
%br
%br
%br

app/views/home/my_recommendation.html.haml
%h2
  <font size = "5">
  Recommendations based on my events
  </font>
  %br
  %br
/Recommends based on event types and event locations
%table.table.table-bordered
  %thead
    %tr
      %th Name:
      %th Add to MyEvents
      %th Recommended Based on This Event
  %tbody
    - @myevents.each do |e|
      - @event = Event.find(e.event_id)
      - @my_events_recommendation = Event.find(:all, :conditions => ['event_type LIKE? OR location LIKE?', @event.event_type, @event.location])
      - @my_events_recommendation.each do |f|
        -if !Myevent.find_by_event_id(f.id) || !Myevent.find_by_user_id(current_user.id)
          %tr
            %td
              = link_to f.name, show_event_path(f.id), class: "linkify-td"
            %td
              = link_to "Add to MyEvents", add_myevent_path(f.id), class: "btn"
            %td
              = @event.name

%br
%br

%h2
  <font size = "5">
  Recommendations based on other user's events
  </font>
  %br
  %br
%table.table.table-bordered
  %thead
    %tr
      %th Name:
      %th Add to MyEvents
      %th Recommended Based on This User
  %tbody
    - @myevents.each do |e|
      - @other_events_recommendation = Myevent.find_all_by_event_id(e.event_id)
      - @other_events_recommendation.each do |f|
        - @other_user_my_events = Myevent.find_all_by_user_id(f.user_id)
        - @other_user_my_events.each do |g|
          - @event = Event.find(g.event_id)
          - @temp_event = Myevent.find_all_by_event_id(@event)
          - @flags = 1
          - @temp_event.each do |e|
            -if e.user_id == current_user.id
              - @flags = 0
          - if @flags == 1
            %tr
              %td
                = link_to @event.name, show_event_path(@event.id), class: "linkify-td"
              %td
                = link_to "Add to MyEvents", add_myevent_path(@event.id), class: "btn"
              %td
                = User.find_by_id(g.user_id).name

%br
%br
= link_to "Back", home_path, class: "btn btn-primary"
%br
%br
%br
%br
%br

app/views/home/public.html.haml
iEvent
%br
%br
%br
%br
%br

app/views/home/search.html.haml
/= form_for @home, :url => { :action => "search"}, :html => {:class => "nifty_form"} do |f|
/	=f.label "Keyword"
/	=f.text_field :search

=form_tag search_results_home_path, :method => 'post' do
	=label_tag :search
	=text_field_tag "search"

	=submit_tag "search", :class => "btn"

=link_to "Back", home_path, class: "btn btn-primary"
%br
%br
%br
%br
%br

app/views/home/search_results.html.haml
Searching For:
=@form
%br
%br

Events
%table.table.table-bordered
  %thead
    %tr               
      %th Name:
      %th Add to My Events:
  %tbody
    - @search.each do |e|
      %tr
        %td 
          = link_to e.name, show_event_path(e.id), class: "linkify-td"
        %td
          = link_to "Add to My Events", add_myevent_path(e.id), class: "btn"

  %br

%br
People:
%table.table.table-bordered
  %thead
    %tr               
      %th Name:
  %tbody
    - @search_person.each do |e|
      %tr
        %td 
          = link_to e.name, show_person_path(e.id), class: "linkify-td"
  %br

%br
Natural Join of Sponsors and Events (Based on the search for the name of the sponsor):
%br
Note: Did not print out all of the Event or the Sponsor's Information. Click on the Name for more information.
%table.table.table-bordered
  %thead
    %tr               
      %th Name of Sponsor:
      %th Event Names:
  %tbody
    - @join.each do |e|
      - @x = Sponsor.find_all_by_sponsorName(e.name)
      - @x.each do |z|
        - @y = Event.find_by_id(z.event_id)
        %tr
          %td 
            = link_to e.name, show_person_path(e.id), class: "linkify-td"
          %td
            = link_to @y.name, show_event_path(@y.id), class: "linkify-td"
            &nbsp;
          %td
            = link_to "Add to My Events", add_myevent_path(@y.id), class: "btn"

%br
%br
= link_to "Back", search_home_path, class: "btn btn-primary"
%br
%br
%br
%br
%br