config/routes.rb
Temp::Application.routes.draw do
    root :to => 'home#public'

    match '/home' => 'home#index', :as => :home
    match '/home/about' => 'home#about', :as => :about

    match '/auth/:provider/callback'  => 'sessions#create'
    match '/auth/failure'             => 'sessions#failure'
    match '/signout'                  => 'sessions#destroy',  :as => :signout
    match '/signin'                   => 'sessions#new',      :as => :signin

    get   '/home/event/web_crawler'  => 'event#web_crawler',   :as => :web_crawler_event

    get   '/home/event/new'         => 'event#new',     :as => :new_event
    post  '/home/event/create'      => 'event#create',  :as => :create_event
    get   '/home/event/:id'         => 'event#show',    :as => :show_event
    get   '/home/event/delete/:id'  => 'event#delete',  :as => :delete_event
    get   '/home/event/:id/update_name' => 'event#update_name', :as => :update_name_event
    post  '/home/event/:id/update_name_save' => 'event#update_name_save', :as => :update_name_save_event
    get   '/home/event/:id/update_type' => 'event#update_type', :as => :update_type_event
    post  '/home/event/:id/update_type_save' => 'event#update_type_save', :as => :update_type_save_event
    get   '/home/event/:id/update_start_time' => 'event#update_start_time', :as => :update_start_time_event
    post  '/home/event/:id/update_start_time_save' => 'event#update_start_time_save', :as => :update_start_time_save_event
    get   '/home/event/:id/update_end_time' => 'event#update_end_time', :as => :update_end_time_event
    post  '/home/event/:id/update_end_time_save' => 'event#update_end_time_save', :as => :update_end_time_save_event
    get   '/home/event/:id/update_cost' => 'event#update_cost', :as => :update_cost_event
    post  '/home/event/:id/update_cost_save' => 'event#update_cost_save', :as => :update_cost_save_event
    get   '/home/event/:id/update_location' => 'event#update_location', :as => :update_location_event
    post  '/home/event/:id/update_location_save' => 'event#update_location_save', :as => :update_location_save_event
    get   '/home/event/:id/update_description' => 'event#update_description', :as => :update_description_event
    post  '/home/event/:id/update_description_save' => 'event#update_description_save', :as => :update_description_save_event
    get   '/home/event/:id/update_registration_deadline' => 'event#update_registration_deadline', :as => :update_registration_deadline_event
    post  '/home/event/:id/update_registration_deadline_save' => 'event#update_registration_deadline_save', :as => :update_registration_deadline_save_event
    get   '/home/event/:id/update_food' => 'event#update_food', :as => :update_food_event
    post  '/home/event/:id/update_food_save' => 'event#update_food_save', :as => :update_food_save_event

    get   '/home/myevent/show'  => 'myevent#show',   :as => :show_myevent
    get  '/home/myevent/add/:id' => 'myevent#add',   :as => :add_myevent
    get   '/home/myevent/remove/:id' =>  'myevent#remove', :as => :remove_myevent 

    get  '/home/my_recommendation'  => 'home#my_recommendation', :as => :my_recommendation_home
    get   '/home/search' => 'home#search', :as => :search_home
    post  '/home/search_results' => 'home#search_results', :as => :search_results_home

    get   '/home/event/:id/host/new'  => 'host#new',  :as => :new_host
    post  '/home/event/:id/host/create' => 'host#create', :as => :create_host
    get   '/home/event/:id/host/delete/' =>'host#delete', :as => :delete_host

    get   '/home/event/:id/sponsor/new'  => 'sponsor#new',  :as => :new_sponsor
    post  '/home/event/:id/sponsor/create' => 'sponsor#create', :as => :create_sponsor
    get   '/home/event/:id/sponsor/delete/' =>'sponsor#delete', :as => :delete_sponsor

    get   '/home/event/:id/speaker/new'  => 'speaker#new',  :as => :new_speaker
    post  '/home/event/:id/speaker/create' => 'speaker#create', :as => :create_speaker
    get   '/home/event/:id/speaker/delete/' =>'speaker#delete', :as => :delete_speaker

    get   '/home/event/:id/artist/new'  => 'artist#new',  :as => :new_artist
    post  '/home/event/:id/artist/create' => 'artist#create', :as => :create_artist
    get   '/home/event/:id/artist/delete/' =>'artist#delete', :as => :delete_artist

    get  '/home/person/new'    => 'person#new',    :as => :new_person
    post '/home/person/create' => 'person#create', :as => :create_person
    get  '/home/person/delete/:id'  => 'person#delete',  :as => :delete_person 
    get  '/home/person/:id'   =>  'person#show',  :as =>  :show_person
    get   '/home/person/:id/update_name' => 'person#update_name', :as => :update_name_person
    post  '/home/person/:id/update_name_save' => 'person#update_name_save', :as => :update_name_save_person
    get   '/home/person/:id/update_address' => 'person#update_address', :as => :update_address_person
    post  '/home/person/:id/update_address_save' => 'person#update_address_save', :as => :update_address_save_person
    get   '/home/person/:id/update_email' => 'person#update_email', :as => :update_email_person
    post  '/home/person/:id/update_email_save' => 'person#update_email_save', :as => :update_email_save_person
    get   '/home/person/:id/update_phone' => 'person#update_phone', :as => :update_phone_person
    post  '/home/person/:id/update_phone_save' => 'person#update_phone_save', :as => :update_phone_save_person

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :name, :event_start_time, :event_end_time, :cost, :location, :description, :registration_deadline, :food
	validates_presence_of :name#, :event_type, :location
	validates_uniqueness_of :name

	belongs_to :user
	has_many :myevents
	has_many :hosts
	has_many :speakers
	has_many :artists
	has_many :sponsors
end

app/controllers/event_controller.rb
class EventController < ApplicationController

	def web_crawler
		require 'net/http'
		require 'nokogiri'
		require 'open-uri'

		#Event = Struct.new(:speaker, :date, :time, :location, :sponsor)
		#def get_html( )
    	# Gets the source for all the event pages
		source = Net::HTTP.get(URI('http://illinois.edu/calendar/list/7'))
		# Time for RegEx
		# Look for all strings that match this pattern..
		# http://illinois.edu/calendar/detail/7?eventId=[NUMBERS]
		# within source
		reg = source.scan(/http:\/\/illinois\.edu\/calendar\/detail\/7\?eventId=[0-9]+/)
		reg = reg.uniq
		event_array = []
		for i in 0..30#reg.length()-1
			# For every match in reg we append it to the event array
			event_array << reg[i]
		end
		# Create an event struct
		/Event1 = Struct.new(:name, :speaker, :date, :time, :location, :sponsor, :cost, :event_t, :desc)/
		output = [] 
		sponsor_output = []
		#person_output = []
		# NOTE : There are about 550+ events in event_array, it took upwards of 15min to crawl and parse them all.
		# I have a feeling it should be faster than that though
		for i in 0..30#event_array.length()-1
			# For every event, grab the source of the page
			eventsource = Nokogiri::HTML(open(event_array[i]))
			# array a holds the all the type of applicable attributes on the page(eg. cost, date, etc)
			# array b holds the respective values of each type
			a = eventsource.xpath('//*[contains(concat( " ", @class, " " ), concat( " ", "column-label", " " ))]')
			b = eventsource.xpath('//*[contains(concat( " ", @class, " " ), concat( " ", "column-info", " " ))]')
			# declare vars outside loop for access
			name = eventsource.css('div#event-wrapper h2').text.to_s.gsub!(/(<[^>]*>)|\n|\t/s) {""}
			date = ""
			location = ""
			sponsor = ""
			#speaker = ""
			#time = ""
			eventtype = ""
			cost = ""
			desc = eventsource.css("div.description-row").text.to_s
			# assigns attributes to their respective values
			for i in 0..a.length-1
				a[i].text.to_s == "Date " ? date = b[i].text.to_s : date = date
				a[i].text.to_s == "Location " ? location = b[i].text.to_s : location = location
				a[i].text.to_s == "Sponsor " ? sponsor = b[i].text.to_s : sponsor = sponsor
				#a[i].text.to_s == "Speaker " ? speaker = b[i].text.to_s : speaker = speaker
				#a[i].text.to_s == "Time " ? time = b[i].text.to_s : time = time
				a[i].text.to_s == "Event type " ? eventtype = b[i].text.to_s : eventtype = eventtype
				a[i].text.to_s == "Cost " ? cost = b[i].text.to_s : cost = cost
				# to satisfy validates_precense of, i'm not sure how to make ruby do nothing so i just assigned it back to itself
				eventtype == "" ? eventtype = "UIUC" : eventtype = eventtype
				location == "" ? location = "N/A" : location = location
			end
			new_event = Event.new
			new_event.name = name
			new_event.location = location
			new_event.event_type = eventtype
			new_event.cost = cost
			new_event.event_start_time = date
			new_event.description = desc
			person = Person.new
			person.name = sponsor
			person.save
			#person_output << person
			sponsor = Sponsor.new
			sponsor.sponsorName = person.name
			#new_event = Event.new(name, speaker, date, time, location, sponsor, cost, eventtype, desc)
			output << new_event
			sponsor_output << sponsor
		end
		for i in 0..output.length()-1
			@newevent = Event.new
			@newevent.name = output[i].name
			@newevent.location = output[i].location
			@newevent.event_type = output[i].event_type
			@newevent.cost = output[i].cost
			@newevent.event_start_time = output[i].event_start_time
			@newevent.description = output[i].description
			#@newevent.createdby_user_id = 1234567890
			#@personnew = Person.new
			#@personnew.name = person_output[2].name
			#@personnew.save
			@newsponsor = Sponsor.new
			@newsponsor.sponsorName = sponsor_output[i].sponsorName
			if @newevent.save
				@newsponsor.event_id = @newevent.id
				@newsponsor.save
			end
		end
		redirect_to home_path and return
	end


	def show
		@id = params[:id]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "That event does not exist!"
			redirect_to home_path and return
		end
	end

	def new
		@event = Event.new
	end


	def create
		@form = params[:event]
		@event = Event.new
		@event.name = @form[:name]
		@event.event_start_time = Date.new( @form["event_start_time(1i)"].to_i, @form["event_start_time(2i)"].to_i, @form["event_start_time(3i)"].to_i)
		@event.event_end_time = Date.new( @form["event_end_time(1i)"].to_i, @form["event_end_time(2i)"].to_i, @form["event_end_time(3i)"].to_i)
		@event.cost = @form[:cost]
		@event.location = @form[:location]
		@event.description = @form[:description]
		@event.registration_deadline = Date.new( @form["registration_deadline(1i)"].to_i, @form["registration_deadline(2i)"].to_i, @form["registration_deadline(3i)"].to_i)
		@event.food = @form[:food]
		@event.event_type = @form[:event_type]
		@event.createdby_user_id = current_user.id
		if @event.save
			flash[:notice] = "#{@event.name} has been made."
			redirect_to home_path and return
		else
			flash[:warning] = "Invalid event, try again. Make sure to fill out a Name!"
			redirect_to new_event_path and return
		end
	end

	def update_name
		@event = Event.new
	end

	def update_name_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.name = @form[:name]
			if@event.save
				flash[:notice] = "Event name has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Invalid event name, try again"
				redirect_to update_name_event_path and return
			end
		end
	end

	def update_type
		@event = Event.new
	end

	def update_type_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.event_type = @form[:event_type]
			if@event.save
				flash[:notice] = "Event type has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event type has failed, try again"
				redirect_to update_type_event_path and return
			end
		end
	end


	def update_start_time
		@event = Event.new
	end

	def update_start_time_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.event_start_time = Date.new( @form["event_start_time(1i)"].to_i, @form["event_start_time(2i)"].to_i, @form["event_start_time(3i)"].to_i)
			if@event.save
				flash[:notice] = "Event start time has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event start time has failed, try again"
				redirect_to update_start_time_event_path and return
			end
		end
	end

	def update_end_time
		@event = Event.new
	end

	def update_end_time_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.event_end_time = Date.new( @form["event_end_time(1i)"].to_i, @form["event_end_time(2i)"].to_i, @form["event_end_time(3i)"].to_i)
			if@event.save
				flash[:notice] = "Event end time has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event end time has failed, try again"
				redirect_to update_end_time_event_path and return
			end
		end
	end

	def update_cost
		@event = Event.new
	end

	def update_cost_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.cost = @form[:cost]
			if@event.save
				flash[:notice] = "Event cost has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event cost has failed, try again"
				redirect_to update_cost_event_path and return
			end
		end
	end

	def update_location
		@event = Event.new
	end

	def update_location_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.location = @form[:location]
			if@event.save
				flash[:notice] = "Event location has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event location has failed, try again"
				redirect_to update_location_event_path and return
			end
		end
	end

	def update_description
		@event = Event.new
	end

	def update_description_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.description = @form[:description]
			if@event.save
				flash[:notice] = "Event description has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event description has failed, try again"
				redirect_to update_description_event_path and return
			end
		end
	end


	def update_registration_deadline
		@event = Event.new
	end

	def update_registration_deadline_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.registration_deadline = Date.new( @form["registration_deadline(1i)"].to_i, @form["registration_deadline(2i)"].to_i, @form["registration_deadline(3i)"].to_i)
			if@event.save
				flash[:notice] = "Event registration deadline has been modified"
				redirect_to show_event_path and return
			else
				flash[:warning] = "Event registration deadline has failed, try again"
				redirect_to update_registration_deadline_event_path and return
			end
		end
	end

	def update_food
		@event = Event.new
	end

	def update_food_save
		@id = params[:id]
		@form = params[:event]
		@event = Event.find_by_id(@id)
		if !@event
			flash[:warning] = "Event does not exist."
		else
			@event.food = @form[:food]
			if@event.save
				flash[:notice] = "Event food has been modified"
				redirect_to show_event_path and return
			else

app/views/event/new.html.haml
= form_for @event, :url => { :action => "create"}, :html => {:class => "nifty_form"} do |f|
	= f.label :name
	= f.text_field :name
	= f.label :event_type
	= f.text_field :event_type
	= f.label :event_start_time
	= f.date_select :event_start_time, :end_year => Time.now.year+5, :start_year => Time.now.year-2, :order => [:month, :day, :year]
	= f.label :event_end_time
	= f.date_select :event_end_time, :end_year => Time.now.year+5, :start_year => Time.now.year-2, :order => [:month, :day, :year]
	= f.label "Cost in dollars"
	= f.text_field	:cost
	= f.label :location
	= f.text_field :location
	= f.label :description
	= f.text_field :description
	= f.label :registration_deadline
	= f.date_select :registration_deadline, :end_year => Time.now.year+5, :start_year => Time.now.year-2, :order => [:month, :day, :year]
	= f.label :food
	= f.select :food, ['No','Yes']
	%br
	%br

	=f.submit "Create", :class => "btn btn-success"

	%br
	%br
	%br
	=link_to "Back", home_path, :class => "btn btn-primary"
	%br
	%br
	%br

app/views/event/show.html.haml
%h2
	<font size = "7">
	= @event.name
	Details
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Name", update_name_event_path, :class => "btn btn-mini"
	</font>
%br
%br

-if @event.event_type != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Event Type </font>
	%br
	-if @event.event_type != nil
		= @event.event_type
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Type", update_type_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if @event.event_start_time != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Event Start Date </font>
	%br
	-if @event.event_start_time != nil
		= @event.event_start_time.to_s(:long)
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Start Time", update_start_time_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if @event.event_end_time != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Event End Date </font>
	%br
	-if @event.event_end_time != nil
		= @event.event_end_time.to_s(:long)
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event End Time", update_end_time_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if @event.cost != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Cost to attend</font>
	%br
	-if @event.cost != nil
		= @event.cost
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Cost", update_cost_event_path, :class => "btn btn-mini"
	%br	
	%br
	%br

-if @event.location != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Location </font>
	%br
	-if @event.location != nil
		= @event.location
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Location", update_location_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if @event.description != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Description</font>
	%br
	-if @event.description != nil
		= @event.description
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Description", update_description_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if @event.registration_deadline != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Registration Deadline</font>
	%br
	-if @event.registration_deadline != nil
		= @event.registration_deadline.to_s(:long)
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Registration Deadline", update_registration_deadline_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if @event.food != nil || current_user.id == @event.createdby_user_id
	<font size = "5"> Is there food? </font>
	%br
	-if @event.food != nil
		= @event.food
	-if current_user.id == @event.createdby_user_id
		= link_to "Edit Event Food", update_food_event_path, :class => "btn btn-mini"
	%br
	%br
	%br

-if Host.find_by_event_id(@id) != nil
	<font size = "5"> Host</font>
	%br
	-@host = Host.find_all_by_event_id(@id)
	-@host.each do |h|
		= h.hostName
		-if current_user.id == @event.createdby_user_id
			=link_to "delete", delete_host_path, :class => "btn btn-mini"
		%br
	%br
	%br

-if Sponsor.find_by_event_id(@id) != nil
	<font size = "5"> Sponsor</font>
	%br
	-@sponsor = Sponsor.find_all_by_event_id(@id)
	-@sponsor.each do |s|
		=s.sponsorName
		-if current_user.id == @event.createdby_user_id
			=link_to "delete", delete_sponsor_path, :class => "btn btn-mini"
		%br
	%br
	%br


-if Speaker.find_by_event_id(@id) != nil
	<font size = "5"> Speaker</font>
	%br
	-@speaker = Speaker.find_all_by_event_id(@id)
	-@speaker.each do |f|
		=f.speakerName
		-if current_user.id == @event.createdby_user_id
			=link_to "delete", delete_speaker_path, :class => "btn btn-mini"
		%br
	%br
	%br


-if Artist.find_by_event_id(@id) != nil
	<font size = "5"> Artist</font>
	%br
	-@artist = Artist.find_all_by_event_id(@id)
	-@artist.each do |a|
		=a.artistName
		-if current_user.id == @event.createdby_user_id
			=link_to "delete", delete_artist_path, :class => "btn btn-mini"
		%br
	%br
	%br

-if current_user.id == @event.createdby_user_id
	= link_to "Add Host", new_host_path, :class => "btn"
	= link_to "Add Sponsor", new_sponsor_path, :class => "btn"
	= link_to "Add Speaker", new_speaker_path, :class => "btn"
	= link_to "Add Artist", new_artist_path, :class => "btn"
	%br
	%br
	%br

-if current_user.id == @event.createdby_user_id #|| current_user.id == 1
	= link_to "Delete Event", delete_event_path(@id), :class => "btn btn-danger"
	%br
	%br
	%br

= link_to "Add to MyEvents", add_myevent_path(@event.id), class: "btn"
%br
%br

= link_to "Back", home_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_cost.html.haml
= form_for @event, :url => { :action => "update_cost_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Cost in Dollars"
	= f.text_field :cost
	%br
	%br

	=f.submit "Update Cost", :class => "btn btn-success"

%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_description.html.haml
= form_for @event, :url => { :action => "update_description_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Description"
	= f.text_field :description
	%br
	%br

	=f.submit "Update Description", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_end_time.html.haml
= form_for @event, :url => { :action => "update_end_time_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New End Date"
	= f.date_select :event_end_time, :end_year => Time.now.year+5, :start_year => Time.now.year-2, :order => [:month, :day, :year]
	%br
	%br

	=f.submit "Update End Date", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_food.html.haml
= form_for @event, :url => { :action => "update_food_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Food"
	= f.select :food, ['No','Yes']
	%br
	%br

	=f.submit "Update Food", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_location.html.haml
= form_for @event, :url => { :action => "update_location_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Location"
	= f.text_field :location
	%br
	%br

	=f.submit "Update Location", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_name.html.haml
= form_for @event, :url => { :action => "update_name_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Name"
	= f.text_field :name
	%br
	%br

	=f.submit "Update Name", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_registration_deadline.html.haml
= form_for @event, :url => { :action => "update_registration_deadline_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Registration Deadline"
	= f.date_select :registration_deadline, :end_year => Time.now.year+5, :start_year => Time.now.year-2, :order => [:month, :day, :year]
	%br
	%br

	=f.submit "Update Registration Deadline", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_start_time.html.haml
= form_for @event, :url => { :action => "update_start_time_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Start Date"
	= f.date_select :event_start_time, :end_year => Time.now.year+5, :start_year => Time.now.year-2, :order => [:month, :day, :year]
	%br
	%br

	=f.submit "Update Start Date", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br

app/views/event/update_type.html.haml
= form_for @event, :url => { :action => "update_type_save"}, :html => {:class => "nifty_form"} do |f|
	= f.label "New Type"
	= f.text_field :event_type
	%br
	%br

	=f.submit "Update Type", :class => "btn btn-success"
%br
%br
= link_to "Back", show_event_path, :class => "btn btn-primary"
%br
%br
%br
%br
%br